### ISSUE TITLE
Feature request : hardlink duplicates

### ISSUE THREAD

**Issue by drasill** [jvirkki/dupd#2]
Hi,

I intend to use dupd to create hardlinks of duplicate files.

Is this something you could implement ?
I guess it could be like the "rmsh" option.

**Comment by drasill** [comment]
Ok, I just saw you implemented a `--link` option to the `rmsh`, to generate a script which removes and symlinks the file.

What do you think of having a `--hardlink` option ? or a `--link=hard` ?

Or, like some other dedupers do, use a hardlink when on the same filesystem, and a symlink otherwise ?

**Comment by jvirkki** [comment]
Adding a --hardlink option is easy enough.

However, it won't be an entirely satisfactory solution because dupd doesn't differentiate hard links to a single file from true duplicates so such files will continue to report as duplicates during future scans.

**Comment by jvirkki** [comment]
Added a --hardlink option (with the above caveat).

**Comment by drasill** [comment]
Thank you !
