### ISSUE TITLE
Test 72 fails when ran as root

### ISSUE THREAD

**Issue by Freaky** [jvirkki/dupd#20]
Test 72 tests the result of chmoding files `000`, which obviously root can bypass.  In this event the test should ideally be skipped.

While testing as root is obviously to be discouraged, as a packager I would often be running it as root inside a jail environment.

**Comment by jvirkki** [comment]
I'd figured I'll need a smarter exclude/ignore tagging mechanism sooner or later, I guess it's now.

**Comment by jvirkki** [comment]
Failures can now be ignored when running as root. Applied to tests 72 & 73.
