### ISSUE TITLE
Update macports version

### ISSUE THREAD

**Issue by joostdekeijzer** [jvirkki/dupd#36]
Hi, not sure to report here but since you maintain the dupd port at macports I'll inform here first.

The macports version still is v1.6. I've updated the portfile to use Github and bumped the version to 1.7 in a branch here: https://github.com/joostdekeijzer/macports-ports/tree/dupd

More specific:
https://github.com/joostdekeijzer/macports-ports/commit/011b4d6bd4468f3f85889208b13720fac8951ef4

**Comment by jvirkki** [comment]
Awesome, thank you!
I've had a post-in note here for a long time to update the macports version but had not been able to get to it.

**Comment by catap** [comment]
@joostdekeijzer maybe you can open a PR and @jvirkki will review it? ;)

**Comment by jvirkki** [comment]
Thanks @catap, I see macports now has 1.7.1.
