### ISSUE TITLE
'report' command 'minsize' doesn't specify the size unit

### ISSUE THREAD

**Issue by oliveox** [jvirkki/dupd#38]
Great software, thank you for making it.

**Issue**
I've observed while using it that the --minsize flag doesn't specify the unit. bits, bytes, kB? 

`report - Display the list of duplicates.

       --cut PATHSEG
              Remove  prefix PATHSEG from the file paths in the report output.
              This can reduce clutter in the output  text  if  all  the  files
              scanned share a long identical prefix.

       --minsize SIZE
              Report only duplicate sets which consume at least this much disk
              space.  Note this is the total size occupied by all  the  dupli‐
              cates in a set, not their individual file size.

       --format NAME
              Produce  the report in this output format.  NAME is one of text,
              csv, json.  The default is text.`

**Comment by jvirkki** [comment]
Good catch, thanks.
