### ISSUE TITLE
Files with backticks in name are skipped

### ISSUE THREAD

**Issue by jbruchon** [jvirkki/dupd#5]
In my initial testing of `dupd` I immediately ran into a file with a backtick in the name and that file was skipped as a result. This is because backticks are used for a separator character for the database, but perhaps some sort of workaround can be put in place (character escaping?)

**Comment by jvirkki** [comment]
Yes. See the USAGE doc on --pathsep for more info on this limitation.

The workaround right now is to use --pathsep to set this to a character that is less common in your file set if possible. Ultimately it is a hack/bug that I should fix.

**Comment by jvirkki** [comment]
Sometimes the simplest solution works...

I changed the separator to 0x1C (ASCII file separator). I half expected this to cause problems with SQLite but turns out it works fine.
