### ISSUE TITLE
Allow --path value to be relative or absolute

### ISSUE THREAD

**Issue by jbruchon** [jvirkki/dupd#6]
I would like to change into a directory and run `dupd` on a subdirectory without having to resolve the absolute path of that subdirectory. Unfortunately, the program only accepts the implicit current directory or (with `--path`) absolute paths. It would be very helpful for the program to handle resolving the canonical path for a specified relative path.

**Comment by jvirkki** [comment]
True, I've meant to do this for a while...

**Comment by jvirkki** [comment]
The value of --path (-p) can now be absolute or relative to current directory.
